### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getpid'

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [ClearcodeHQ/mirakuru#111]
```
07-Jul-2016 05:19:31	Error in atexit._run_exitfuncs:
07-Jul-2016 05:19:31	Traceback (most recent call last):
07-Jul-2016 05:19:31	  File "/pyenv/versions/2.7.11/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
07-Jul-2016 05:19:31	    func(*targs, **kargs)
07-Jul-2016 05:19:31	  File "/env/lib/python2.7/site-packages/mirakuru/base.py", line 50, in cleanup_subprocesses
07-Jul-2016 05:19:31	    pids = processes_with_env(ENV_UUID, str(os.getpid()))
07-Jul-2016 05:19:31	AttributeError: 'NoneType' object has no attribute 'getpid'
07-Jul-2016 05:19:31	Error in sys.exitfunc:
07-Jul-2016 05:19:31	Traceback (most recent call last):
07-Jul-2016 05:19:31	  File "/pyenv/versions/2.7.11/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
07-Jul-2016 05:19:31	    func(*targs, **kargs)
07-Jul-2016 05:19:31	  File "/env/lib/python2.7/site-packages/mirakuru/base.py", line 50, in cleanup_subprocesses
07-Jul-2016 05:19:31	    pids = processes_with_env(ENV_UUID, str(os.getpid()))
07-Jul-2016 05:19:31	AttributeError: 'NoneType' object has no attribute 'getpid'

```

**Comment by pwilczynskiclearcode** [comment]
Does `atexit` require importing everything inside body of function again?

**Comment by mmaslowskicc** [comment]
Or http://stackoverflow.com/questions/2572172/referencing-other-modules-in-atexit

**Comment by pwilczynskiclearcode** [comment]
So the answer is - yes it does require.

Maybe instead of importing `os` again we could pass `os` as a positional argument like in the `atexit` docs https://docs.python.org/2/library/atexit.html

**Comment by pwilczynskiclearcode** [comment]
```
7-Jul-2016 09:57:42	======================== 2938 passed in 1172.85 seconds ========================
07-Jul-2016 09:57:42	Error in atexit._run_exitfuncs:
07-Jul-2016 09:57:42	Traceback (most recent call last):
07-Jul-2016 09:57:42	  File "/home/bamboo/.pyenv/versions/2.7.11/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
07-Jul-2016 09:57:42	    func(*targs, **kargs)
07-Jul-2016 09:57:42	  File "/.../env/lib/python2.7/site-packages/mirakuru/base.py", line 51, in cleanup_subprocesses
07-Jul-2016 09:57:42	    pids = processes_with_env(ENV_UUID, str(os.getpid()))
07-Jul-2016 09:57:42	  File "/.../env/lib/python2.7/site-packages/mirakuru/base_env.py", line 52, in processes_with_env_psutil
07-Jul-2016 09:57:42	    for proc in psutil.process_iter():
07-Jul-2016 09:57:42	AttributeError: 'NoneType' object has no attribute 'process_iter'
07-Jul-2016 09:57:42	Error in sys.exitfunc:
07-Jul-2016 09:57:42	Traceback (most recent call last):
07-Jul-2016 09:57:42	  File "/home/bamboo/.pyenv/versions/2.7.11/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
07-Jul-2016 09:57:42	    func(*targs, **kargs)
07-Jul-2016 09:57:42	  File "/.../env/lib/python2.7/site-packages/mirakuru/base.py", line 51, in cleanup_subprocesses
07-Jul-2016 09:57:42	    pids = processes_with_env(ENV_UUID, str(os.getpid()))
07-Jul-2016 09:57:42	  File "/.../env/lib/python2.7/site-packages/mirakuru/base_env.py", line 52, in processes_with_env_psutil
07-Jul-2016 09:57:42	    for proc in psutil.process_iter():
07-Jul-2016 09:57:42	AttributeError: 'NoneType' object has no attribute 'process_iter'
```
