### ISSUE TITLE
Exception when executing dynamodb-local

### ISSUE THREAD

**Issue by xuru** [ClearcodeHQ/mirakuru#134]
_Using: Python 3.5.2_

When using the TCPExecutor to execute the shell script /usr/local/bin/dynamodb-local (installed via homebrew), I get the following exception when exiting the main script.

I'm creating a "manage.py" script according to the flask docs located [here](http://flask.pocoo.org/docs/0.11/cli/#custom-scripts), and it looks like:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Customized for running locally. DO NOT USE IN DEPLOYED ENVIRONMENTS"""
import os
import sys

import click
from flask.cli import FlaskGroup
from mirakuru import TCPExecutor

from myapp.settings import LOCAL_ENVIRONMENTS, get_config

here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here)


def create_myapp_app(info):
    from myapp.app import create_app
    return create_app()


@click.group(cls=FlaskGroup, create_app=create_myapp_app)
def cli():
    """This is a management script for the myapp application."""


if __name__ == '__main__':
    config = get_config()
    executor = None

    if config.NAME in LOCAL_ENVIRONMENTS:
        # Run local dynamo in the background
        executor = TCPExecutor(
            "dynamodb-local",
            host=config.FLYWHEEL_DATABASE_HOST,
            port=config.FLYWHEEL_DATABASE_PORT
        )
        try:
            executor.start()
        except FileNotFoundError as e:
            click.secho("dynamodb-local not found.", fg="red")
            click.secho("To install, you can either use homebrew, "
                        "or follow these instructions: https://goo.gl/OATMn4", fg="red")

    cli()

    if executor is not None:
        executor.stop()
        executor = None
```

And I get the following exception:

```

Exception ignored in: <bound method SimpleExecutor.__del__ of <mirakuru.tcp.TCPExecutor: "dynamodb-l..." 0x10cb522b0>>
Traceback (most recent call last):
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 353, in __del__
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 307, in kill
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 227, in _kill_all_kids
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base_env.py", line 52, in processes_with_env_psutil
TypeError: 'NoneType' object is not callable
```

I'll see if I can look into this and possibly provide a pull request next week.  I kind of looks like it's being garbage cleaned before killing it's subprocesses.  I've seen this before when using **del**, but I can't remember what the solution was...

**Comment by xuru** [comment]
So, in python3, the the destructor is called when it is garbage collected.  The problem is the destructor can be called at any point, and in this case, there is no other reference to it to keep it open.  Also:

> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

So using the Executor as a context manager is a much preferred way of using it (and I don't get the exception when using it this way).  So I think the thing to do is use a try/except in the `__del__` and log a message that makes some sense.

**Comment by fizyk** [comment]
I see there another problem as well. The destructor is the last resort attempt to not leave leaked processes. Here we should also look at the fact, that you attempt to stop the process, which seems to fail (?) and that's why destructor gets called (?) Unless the exiting Flask's cli behaves a bit different and omits our stop.

**Comment by xuru** [comment]
One thing I didn't put in the description: It doesn't happen every time, which suggests a race condition.  Smells like it is executing the __del__ code, and the gc comes along and deletes the object underneath it if it is taking too long.

**Comment by fizyk** [comment]
I'd say that the case when you don't get said exception is when gc comes along before you exit your program.

stop somehow doesn't correctly stop the process and. Maybe command doesn't allow to properly manage the dynamodb-local?

We have a set of fixtures for dynamodb in pytest-dbfixture plugin, and we use a bit different path to start dynamodb:

https://github.com/ClearcodeHQ/pytest-dbfixtures/blob/master/src/pytest_dbfixtures/factories/dynamodb.py#L72

**Comment by fizyk** [comment]
Still have problems with understanding how #135 solves this race condition.

**Comment by xuru** [comment]
It doesn't.  It just gives an indication on what you can do to get around it if you run into the same problem.  I'm not sure there _is_ a way to solve it using the '__del__' destructor.  I think it's just best avoided when possible.

**Comment by fizyk** [comment]
have you checked if instantiating in the same way we do in pytest-dbfixtures help?

**Comment by xuru** [comment]
I'll give it a try and see.  I use homebrew to install dynamodb-local, but it shouldn't be hard to put in the write arguments.

**Comment by xuru** [comment]
I get the same error. Here is the modified code:

```

if __name__ == '__main__':
    config = get_config()
    executor = None

    dynamodb_port = 8000
    delay_arg = ''
    dyno_dir = "/usr/local/Cellar/dynamodb-local"
    path_dynamodb_jar = dyno_dir + "/2016-05-17/libexec/DynamoDBLocal.jar"

    cmd = '''java
        -Djava.library.path=./DynamoDBLocal_lib
        -jar {path_dynamodb_jar}
        -inMemory
        {delay}
        -port {port}'''.format(path_dynamodb_jar=path_dynamodb_jar, port=dynamodb_port, delay=delay_arg, )

    click.echo("cmd: {}".format(cmd))

    if config.NAME in LOCAL_ENVIRONMENTS:
        # Run local dynamo in the background
        executor = TCPExecutor(
            cmd,
            host=config.FLYWHEEL_DATABASE_HOST,
            port=config.FLYWHEEL_DATABASE_PORT
        )
        try:
            executor.start()
        except FileNotFoundError as e:
            click.secho("dynamodb-local not found.", fg="red")
            click.secho("To install, you can either use homebrew, "
                        "or follow these instructions: https://goo.gl/OATMn4", fg="red")

    cli()

    if executor is not None:
        executor.stop()
```

Here is the error I get:
```
$ ./manage.py urls
Environment Local
cmd: java
        -Djava.library.path=./DynamoDBLocal_lib
        -jar /usr/local/Cellar/dynamodb-local/2016-05-17/libexec/DynamoDBLocal.jar
        -inMemory

        -port 8000
Rule                                      Endpoint
-----------------------------------------------------------------------
/auth                                     _default_auth_request_handler
/health                                   check
/static/<path:filename>                   static
/v0/users                                 usersresource
/v0/users/<string:user_id>                userresource
/v0/users/<string:user_id>/profile_image  userprofileimageresource
Exception ignored in: <bound method SimpleExecutor.__del__ of <mirakuru.tcp.TCPExecutor: "java
     ..." 0x1052d6588>>
Traceback (most recent call last):
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 353, in __del__
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 307, in kill
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 227, in _kill_all_kids
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base_env.py", line 52, in processes_with_env_psutil
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/psutil/__init__.py", line 1342, in process_iter
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/psutil/__init__.py", line 1296, in pids
TypeError: 'NoneType' object is not callable
```

Even more interesting, is the traceback is a bit different sometimes, as if it gets cut off at different spots in the code.  It even succeeds about 1 out of 10 times.

```
Traceback (most recent call last):
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 353, in __del__
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 307, in kill
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base.py", line 227, in _kill_all_kids
  File "/Users/plaster/.virtualenvs/myapp/lib/python3.5/site-packages/mirakuru/base_env.py", line 52, in processes_with_env_psutil
TypeError: 'NoneType' object is not callable
```

**Comment by fizyk** [comment]
What intrigues me, is that the stop doesn't actually stops the dynamodb...
```
if executor is not None:
    executor.stop()
    assert not executor.running()
```
